# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy project files
COPY . /app

# Install Python dependencies while ignoring the requires-python check
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir --ignore-requires-python .

# Expose port for FastAPI callback
EXPOSE 5000

# Default command
CMD ["python", "main.py"]
